# Generated by Django 5.1.5 on 2025-03-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0003_customuser_book_added_by_library_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_view", "Can view book"),
                    ("can_create", "Can create book"),
                    ("can_edit", "Can edit book"),
                    ("can_delete", "Can delete book"),
                ]
            },
        ),
    ]
